export const mockedEvent = {
  id: 'a46b00251aa2',
  type: 'EVENT',
  name: 'HSBC Singapore Rugby Sevens 2020',
  description:
    'Singapore National Stadium, 1 Stadium Drive, Singapore 397629, Singapore at 2020-10-10 00:00  <strong>NB this event date/time may vary All subject to change</strong>',
  localDateTime: '2020-10-10T00:00:00',
  geo: {
    city: 'Singapore',
    country: null,
    __typename: 'ProductGeo',
  },
  price: {
    currency: 'AUD',
    amount: '28.73',
    annotation: 'from, 26.6 m/u All channels STS vendor all currencies add 8%, free shipping',
    __typename: 'ProductPrice',
  },
  url: 'https://dev2.sportswhereiam.com/wp-content/uploads/sts/https://graphics.sportswhereiam.com/event/STS49.jpg',
  urlType: 'EMBEDDED',
  variants: [
    {
      id: 'a46b002518a2',
      ticket: null,
      name: 'Premium - 2 day ticket',
      description: '10th October and 11th October. Reserved seating',
      price: {
        currency: 'AUD',
        amount: '263.2',
        annotation: '243.7 m/u All channels STS vendor all currencies add 8%, free shipping',
        __typename: 'ProductPrice',
      },
      attributes: {
        inventory: null,
        groupType: null,
        deliveryOpts: 'ETICKET',
        lowHighSeats: null,
        row: 'n/a',
        section: '10th October and 11th October. Reserved seating',
        splits: '1,2,3,4,5,6,7,8,9,10',
        live: 'true',
        notes: null,
        rdo: null,
        __typename: 'ProductAttributes',
      },
      __typename: 'ProductVariant',
    },
    {
      id: 'a46b002519ab',
      ticket: null,
      name: 'Category 1 - 2 day ticket',
      description: '10th October and 11th October. Open seating',
      price: {
        currency: 'AUD',
        amount: '170.85',
        annotation: '158.19 m/u All channels STS vendor all currencies add 8%, free shipping',
        __typename: 'ProductPrice',
      },
      attributes: {
        inventory: null,
        groupType: null,
        deliveryOpts: 'ETICKET',
        lowHighSeats: null,
        row: 'n/a',
        section: '10th October and 11th October. Open seating',
        splits: '1,2,3,4,5,6,7,8,9,10',
        live: 'true',
        notes: null,
        rdo: null,
        __typename: 'ProductAttributes',
      },
      __typename: 'ProductVariant',
    },
    {
      id: 'a46b002519aa',
      ticket: null,
      name: 'Category 2 - 2 day ticket',
      description: '10th October and 11th October. Open seating',
      price: {
        currency: 'AUD',
        amount: '57.98',
        annotation: '53.68 m/u All channels STS vendor all currencies add 8%, free shipping',
        __typename: 'ProductPrice',
      },
      attributes: {
        inventory: null,
        groupType: null,
        deliveryOpts: 'ETICKET',
        lowHighSeats: null,
        row: 'n/a',
        section: '10th October and 11th October. Open seating',
        splits: '1,2,3,4,5,6,7,8,9,10',
        live: 'true',
        notes: null,
        rdo: null,
        __typename: 'ProductAttributes',
      },
      __typename: 'ProductVariant',
    },
    {
      id: 'a46b002519a9',
      ticket: null,
      name: 'Category 1 - 2 day youth ticket',
      description: '10th October and 11th October. Open seating. 4 to 18 years old',
      price: {
        currency: 'AUD',
        amount: '68.24',
        annotation: '63.18 m/u All channels STS vendor all currencies add 8%, free shipping',
        __typename: 'ProductPrice',
      },
      attributes: {
        inventory: null,
        groupType: null,
        deliveryOpts: 'ETICKET',
        lowHighSeats: null,
        row: 'n/a',
        section: '10th October and 11th October. Open seating. 4 to 18 years old',
        splits: '1,2,3,4,5,6,7,8,9,10',
        live: 'true',
        notes: null,
        rdo: null,
        __typename: 'ProductAttributes',
      },
      __typename: 'ProductVariant',
    },
    {
      id: 'a46b002519a8',
      ticket: null,
      name: 'Category 2 - 2 day youth ticket',
      description: '10th October and 11th October. Open seating. 4 to 18 years old',
      price: {
        currency: 'AUD',
        amount: '28.73',
        annotation: '26.6 m/u All channels STS vendor all currencies add 8%, free shipping',
        __typename: 'ProductPrice',
      },
      attributes: {
        inventory: null,
        groupType: null,
        deliveryOpts: 'ETICKET',
        lowHighSeats: null,
        row: 'n/a',
        section: '10th October and 11th October. Open seating. 4 to 18 years old',
        splits: '1,2,3,4,5,6,7,8,9,10',
        live: 'true',
        notes: null,
        rdo: null,
        __typename: 'ProductAttributes',
      },
      __typename: 'ProductVariant',
    },
    {
      id: 'a46b002519af',
      ticket: null,
      name: 'Category 1 - 2 day family package',
      description: '10th October and 11th October. Open seating. 2 adults and 2 youths 4 to 18 years old',
      price: {
        currency: 'AUD',
        amount: '378.64',
        annotation: '350.59 m/u All channels STS vendor all currencies add 8%, free shipping',
        __typename: 'ProductPrice',
      },
      attributes: {
        inventory: null,
        groupType: null,
        deliveryOpts: 'ETICKET',
        lowHighSeats: null,
        row: 'n/a',
        section: '10th October and 11th October. Open seating. 2 adults and 2 youths 4 to 18 years old',
        splits: '1,2,3,4,5,6,7,8,9,10',
        live: 'true',
        notes: null,
        rdo: null,
        __typename: 'ProductAttributes',
      },
      __typename: 'ProductVariant',
    },
    {
      id: 'a46b002519ae',
      ticket: null,
      name: 'Category 2 - 2 day family package',
      description: '10th October and 11th October. Open seating. 2 adults and 2 youths 4 to 18 years old',
      price: {
        currency: 'AUD',
        amount: '133.41',
        annotation: '123.52 m/u All channels STS vendor all currencies add 8%, free shipping',
        __typename: 'ProductPrice',
      },
      attributes: {
        inventory: null,
        groupType: null,
        deliveryOpts: 'ETICKET',
        lowHighSeats: null,
        row: 'n/a',
        section: '10th October and 11th October. Open seating. 2 adults and 2 youths 4 to 18 years old',
        splits: '1,2,3,4,5,6,7,8,9,10',
        live: 'true',
        notes: null,
        rdo: null,
        __typename: 'ProductAttributes',
      },
      __typename: 'ProductVariant',
    },
  ],
  __typename: 'EventProduct',
};
